# Generated by Django 4.2.9 on 2024-02-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_pic', models.ImageField(upload_to='productImage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
